name: Publish

on:
    workflow_dispatch:
        inputs:
            update-type:
                type: choice
                description: Update Type
                options:
                    - patch
                    - minor
                    - major

jobs:
    publish:
        if: github.ref_type == 'branch' && github.ref_name == 'main'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4

            - name: Clean install
              run: |
                  npm clean-install

            - name: Format
              run: |
                  npm run format-check

            - name: Lint
              run: |
                  npm run lint

            - name: Build
              run: |
                  npm run build

            - name: Test
              run: |
                  npm test

            - name: Get current version
              id: package-version
              uses: martinbeentjes/npm-get-version-action@v1.3.1

            - name: Bump version and push tag
              id: bump-and-tag
              uses: laputansoft/github-tag-action@v4.6
              with:
                  default_bump: ${{ inputs.update-type }}
                  dry_run: true
                  github_token: ${{ secrets.github-token }}
                  release_branches: .*
                  tag: ${{ steps.package-version.outputs.current-version }}

            - name: Echo new tag
              env:
                  NEW_TAG: ${{ steps.bump-and-tag.outputs.new_tag }}
              run: |
                  echo "new tag: $NEW_TAG"

            - name: Echo latest hash
              env:
                  LATEST_HASH: ${{ steps.bump-and-tag.outputs.latest_hash }}
              run: |
                  echo "latest hash: $LATEST_HASH"

            # - name: Publish to npm
            #   uses: JS-DevTools/npm-publish@v3
            #   with:
            #       access: public
            #       token: ${{ secrets.NPM_TOKEN }}
