name: Pull Request

on:
    pull_request:
        branches:
            - main

jobs:
    pull-request:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4

            - name: Clean Install
              run: |
                  npm clean-install

            - name: Build
              run: |
                  npm run build

            - name: Test
              run: |
                  npm test
